// AUTO-GENERATED by scripts/generate_schema.py from defaults/OptiScaler.reference.ini
// Do not edit by hand.
import type { OptionMeta } from "../types";

export const GENERATED_OPTIONS: OptionMeta[] = [
  {
    "section": "Upscalers",
    "key": "Dx11Upscaler",
    "label": "Dx11 Upscaler",
    "description": "Select Upscaler for Dx11 games",
    "default": "fsr22",
    "type": "enum",
    "options": [
      "fsr22",
      "fsr31",
      "xess",
      "xess_12",
      "fsr21_12",
      "fsr22_12",
      "fsr31_12",
      "dlss"
    ],
    "optionLabels": {
      "fsr22": "fsr22 \u2014 native DX11",
      "fsr31": "fsr31 \u2014 native DX11",
      "xess": "xess \u2014 native DX11, Arc only",
      "xess_12": "xess_12 \u2014 dx11on12",
      "fsr21_12": "fsr21_12 \u2014 dx11on12",
      "fsr22_12": "fsr22_12 \u2014 dx11on12",
      "fsr31_12": "fsr31_12 \u2014 dx11on12, FSR4"
    }
  },
  {
    "section": "Upscalers",
    "key": "Dx12Upscaler",
    "label": "Dx12 Upscaler",
    "description": "Select Upscaler for Dx12 games",
    "default": "xess",
    "type": "enum",
    "options": [
      "xess",
      "fsr21",
      "fsr22",
      "fsr31",
      "dlss"
    ],
    "optionLabels": {
      "fsr31": "fsr31 \u2014 also for FSR4"
    }
  },
  {
    "section": "Upscalers",
    "key": "VulkanUpscaler",
    "label": "Vulkan Upscaler",
    "description": "Select Upscaler for Vulkan games",
    "default": "fsr22",
    "type": "enum",
    "options": [
      "fsr21",
      "fsr22",
      "fsr31",
      "xess",
      "fsr21_12",
      "fsr31_12",
      "dlss"
    ],
    "optionLabels": {
      "fsr21": "fsr21 \u2014 native VK",
      "fsr22": "fsr22 \u2014 native VK",
      "fsr31": "fsr31 \u2014 native VK",
      "xess": "xess \u2014 native VK",
      "fsr21_12": "fsr21_12 \u2014 VKon12",
      "fsr31_12": "fsr31_12 \u2014 VKon12, FSR4"
    }
  },
  {
    "section": "FrameGen",
    "key": "Enabled",
    "label": "Enabled",
    "description": "Enables Frame Generation",
    "default": "false",
    "type": "bool"
  },
  {
    "section": "FrameGen",
    "key": "FGInput",
    "label": "FG Input",
    "description": "Selected FG Input/Source dlssg     - Can be used with any FG Output. Supports Hudless out of the box. Limited to games that use Streamline v2 and DLSSG nukems    - Limited to FSR 3 FG. Requires DLSSG in the game. Supports Hudless out of the box. Uses Streamline swapchain for pacing. fsrfg     - Can be used with any FG Output. Supports Hudless out of the box. upscaler  - Upscaler must be enabled. Can be used with any FG Output, but might be imperfect with some. To prevent UI glitching, Hudfix is required fsrfg30   - Can be used with any FG Output. Supports Hudless out of the box.",
    "default": "nofg",
    "type": "enum",
    "options": [
      "nofg",
      "dlssg",
      "nukems",
      "fsrfg",
      "upscaler",
      "fsrfg30"
    ]
  },
  {
    "section": "FrameGen",
    "key": "FGOutput",
    "label": "FG Output",
    "description": "Selected FG Output fsrfg  - requires amd_fidelityfx_dx12.dll or amd_fidelityfx_loader_dx12.dll + amd_fidelityfx_framegeneration_dx12.dll xefg   - requires libxess_fg.dll, libxell.dll and latest fakenvapi dll nukems - requires dlssg_to_fsr3_amd_is_better.dll, AMD/Intel GPU users need to add fakenvapi as well",
    "default": "nofg",
    "type": "enum",
    "options": [
      "nofg",
      "fsrfg",
      "xefg",
      "nukems"
    ]
  },
  {
    "section": "FrameGen",
    "key": "FTInput",
    "label": "FT Input",
    "description": "Frametime source, would affect frame pacing 0: Input (DLSSG/FSRFG/OptiFG) | 1: Time between Present calls | 2: Zero (Only for XeFG)",
    "default": "0",
    "type": "bool"
  },
  {
    "section": "FrameGen",
    "key": "DebugView",
    "label": "Debug View",
    "description": "Enables Frame Generation Debug View",
    "default": "false",
    "type": "bool"
  },
  {
    "section": "FrameGen",
    "key": "DrawUIOverFG",
    "label": "Draw UI Over FG",
    "description": "Draw UI over FG, requires Hudless and a UI texture, mostly for FSR FG",
    "default": "false",
    "type": "bool"
  },
  {
    "section": "FrameGen",
    "key": "UIPremultipliedAlpha",
    "label": "UI Premultiplied Alpha",
    "description": "Sets the type of a provided UI texture, with DrawUIOverFG + FSR FG it will change how the UI looks",
    "default": "true",
    "type": "bool"
  },
  {
    "section": "FrameGen",
    "key": "DisableHudless",
    "label": "Disable Hudless",
    "description": "Control Hudless, even if FG source provides one",
    "default": "false",
    "type": "bool"
  },
  {
    "section": "FrameGen",
    "key": "DisableUI",
    "label": "Disable UI",
    "description": "Control a UI texture, even if FG source provides one",
    "default": "true",
    "type": "bool"
  },
  {
    "section": "FrameGen",
    "key": "SkipReset",
    "label": "Skip Reset",
    "description": "Ignores Reset signals coming from FG inputs",
    "default": "false",
    "type": "bool"
  },
  {
    "section": "FrameGen",
    "key": "RectLeft",
    "label": "Rect Left",
    "description": "Defines FG rectangle",
    "default": "whole screen",
    "type": "int"
  },
  {
    "section": "FrameGen",
    "key": "RectTop",
    "label": "Rect Top",
    "description": "",
    "type": "int",
    "default": "auto",
    "inheritedFrom": "RectLeft"
  },
  {
    "section": "FrameGen",
    "key": "RectWidth",
    "label": "Rect Width",
    "description": "",
    "type": "int",
    "default": "auto",
    "inheritedFrom": "RectTop"
  },
  {
    "section": "FrameGen",
    "key": "RectHeight",
    "label": "Rect Height",
    "description": "",
    "type": "int",
    "default": "auto",
    "inheritedFrom": "RectWidth"
  },
  {
    "section": "FrameGen",
    "key": "AllowedFrameAhead",
    "label": "Allowed Frame Ahead",
    "description": "Number of frames the FG is allowed to be ahead of the game Might prevent FG on/off switching but also might cause issues",
    "default": "1",
    "type": "int",
    "min": 1,
    "max": 3
  },
  {
    "section": "FrameGen",
    "key": "DepthValidNow",
    "label": "Depth Valid Now",
    "description": "Always tag Depth as ValidNow Will use more VRAM but needed for Uniscaler",
    "default": "false",
    "type": "bool"
  },
  {
    "section": "FrameGen",
    "key": "VelocityValidNow",
    "label": "Velocity Valid Now",
    "description": "Always tag Velocity as ValidNow Will use more VRAM but needed for Uniscaler",
    "default": "false",
    "type": "bool"
  },
  {
    "section": "FrameGen",
    "key": "HudlessValidNow",
    "label": "Hudless Valid Now",
    "description": "Always tag Hudless as ValidNow Will use more VRAM but needed for Uniscaler",
    "default": "false",
    "type": "bool"
  },
  {
    "section": "FrameGen",
    "key": "OnlyAcceptFirstHudless",
    "label": "Only Accept First Hudless",
    "description": "If source tags more than one hudless only use first one",
    "default": "false",
    "type": "bool"
  },
  {
    "section": "FrameGen",
    "key": "PreserveSwapChain",
    "label": "Preserve Swap Chain",
    "description": "Preserve and prevent releasing FG swapchain Might prevents crashes when releasing swapchain",
    "default": "true",
    "type": "bool"
  },
  {
    "section": "FrameGen",
    "key": "SkipResizeBuffers",
    "label": "Skip Resize Buffers",
    "description": "Skip ResizeBuffers call to swapchain If old and new descriptions are the same Prevents crashes after ResizeBuffers calls",
    "default": "false",
    "type": "bool"
  },
  {
    "section": "FrameGen",
    "key": "ModifyBufferState",
    "label": "Modify Buffer State",
    "description": "Normally after ResizeBuffers call swapchain buffers should be in state COMMON, when this option enabled OptiScaler will try to set swapchain buffer states when skipping ResizeBuffers call Might cause crashes or fix them",
    "default": "false",
    "type": "bool"
  },
  {
    "section": "FrameGen",
    "key": "ModifySCIndex",
    "label": "Modify SC Index",
    "description": "Normally after ResizeBuffers call swapchain current index should be 0, when this option enabled OptiScaler will try to set swapchain index by calling present until index reaches 0 Might cause crashes or fix them",
    "default": "false",
    "type": "bool"
  },
  {
    "section": "FSRFG",
    "key": "DebugTearLines",
    "label": "Debug Tear Lines",
    "description": "Enables FSR3.1 Frame Generation Tear Lines",
    "default": "false",
    "type": "bool"
  },
  {
    "section": "FSRFG",
    "key": "DebugResetLines",
    "label": "Debug Reset Lines",
    "description": "Enables FSR3.1 Frame Generation interpolation skip lines",
    "default": "false",
    "type": "bool"
  },
  {
    "section": "FSRFG",
    "key": "DebugPacingLines",
    "label": "Debug Pacing Lines",
    "description": "Enables FSR3.1 Frame Generation pacing lines",
    "default": "false",
    "type": "bool"
  },
  {
    "section": "FSRFG",
    "key": "AllowAsync",
    "label": "Allow Async",
    "description": "Enables Async FSR3.1 Frame Generation",
    "default": "false",
    "type": "bool"
  },
  {
    "section": "FSRFG",
    "key": "UseMutexForSwapchain",
    "label": "Use Mutex For Swapchain",
    "description": "Enables usage of mutex for FG swapchain present calls Disabling it might improve performance in cost of stability",
    "default": "true",
    "type": "bool"
  },
  {
    "section": "FSRFG",
    "key": "FramePacingTuning",
    "label": "Frame Pacing Tuning",
    "description": "Frame Pace Tuning Enables custom Frame Pace Tuning parameters",
    "default": "true",
    "type": "bool"
  },
  {
    "section": "FSRFG",
    "key": "FPTSafetyMarginInMs",
    "label": "FPT Safety Margin In Ms",
    "description": "This info is from: https://github.com/GPUOpen-LibrariesAndSDKs/FidelityFX-SDK/blob/54fbaafdc34716811751bea5032700e78f5a0f33/ffx-api/include/ffx_api/ffx_api_types.h#L197 Default Tuning safetyMarginInMs==0.1ms and varianceFactor==0.1. Tuning set A safetyMarginInMs==0.75ms, and varianceFactor==0.1. Tuning Set B safetyMarginInMs==0.01ms and varianceFactor==0.3. If your game when using FG, frame rate is running at unexpectly low frame rate, after gradual transition from rendering complex to easy scene complexity, you could try setting \"Tuning Set B\" to recover lost FPS at cost of a bit higher variance. OptiScaler will use Tuning B as default Frame Pace Tuning Sets safety margin",
    "default": "0.01",
    "type": "float"
  },
  {
    "section": "FSRFG",
    "key": "FPTVarianceFactor",
    "label": "FPT Variance Factor",
    "description": "Frame Pace Tuning Sets variance factor",
    "default": "0.3",
    "type": "float",
    "min": 0.0,
    "max": 1.0
  },
  {
    "section": "FSRFG",
    "key": "FPTHybridSpin",
    "label": "FPT Hybrid Spin",
    "description": "Frame Pace Tuning Allows pacing spinlock to sleep, should reduce CPU usage Might cause slow ramp up of FPS",
    "default": "false",
    "type": "bool"
  },
  {
    "section": "FSRFG",
    "key": "FPTHybridSpinTime",
    "label": "FPT Hybrid Spin Time",
    "description": "Frame Pace Tuning How long to spin if FPTHybridSpin is true. Measured in timer resolution units. Not recommended to go below 2. Will result in frequent overshoots",
    "default": "2",
    "type": "int",
    "min": 0
  },
  {
    "section": "FSRFG",
    "key": "FPTWaitForSingleObjectOnFence",
    "label": "FPT Wait For Single Object On Fence",
    "description": "Frame Pace Tuning Allows WaitForSingleObject instead of spinning for fence value",
    "default": "false",
    "type": "bool"
  },
  {
    "section": "FSRFG",
    "key": "EnableWatermark",
    "label": "Enable Watermark",
    "description": "Enable FSR-FG Redstone Watermark",
    "default": "false",
    "type": "bool"
  },
  {
    "section": "XeFG",
    "key": "IgnoreInitChecks",
    "label": "Ignore Init Checks",
    "description": "Skips pre ini checks for XeFG Might cause bad IQ or crashes!",
    "default": "false",
    "type": "bool"
  },
  {
    "section": "XeFG",
    "key": "InterpolationCount",
    "label": "Interpolation Count",
    "description": "Sets interpolated frame count (MFG)",
    "default": "1",
    "type": "enum",
    "options": [
      "1",
      "2",
      "3"
    ],
    "optionLabels": {
      "1": "2X",
      "2": "3X",
      "3": "4X"
    }
  },
  {
    "section": "XeFG",
    "key": "DepthInverted",
    "label": "Depth Inverted",
    "description": "XeFG DepthInverted flag",
    "default": "true",
    "type": "bool"
  },
  {
    "section": "XeFG",
    "key": "UIComposition",
    "label": "UI Composition",
    "description": "Disable UI interpolation Only works when hudless is provided",
    "default": "false",
    "type": "bool"
  },
  {
    "section": "XeFG",
    "key": "JitteredMV",
    "label": "Jittered MV",
    "description": "XeFG JitteredMV flag",
    "default": "false",
    "type": "bool"
  },
  {
    "section": "XeFG",
    "key": "HighResMV",
    "label": "High Res MV",
    "description": "XeFG HighResMV flag",
    "default": "false",
    "type": "bool"
  },
  {
    "section": "XeFG",
    "key": "DebugView",
    "label": "Debug View",
    "description": "Enables XeFG debug squares",
    "default": "false",
    "type": "bool"
  },
  {
    "section": "XeFG",
    "key": "ForceBorderless",
    "label": "Force Borderless",
    "description": "Forces Borderless mode instead of Exclusive Fullscreen It might cause stability issues on mode changes or IQ issues when exclusive fullscreen mode is smaller than diplay resolution",
    "default": "false",
    "type": "bool"
  },
  {
    "section": "OptiFG",
    "key": "DisableHUDFix",
    "label": "Disable HUD Fix",
    "description": "Disables HUDFix resource tracking along with reducing CPU overhead when used with ML Frame Generators which handle HUD elements",
    "default": "false",
    "type": "bool"
  },
  {
    "section": "OptiFG",
    "key": "HUDFix",
    "label": "HUD Fix",
    "description": "Enables HUDFix Hudless tracking for Frame Generation Might cause crashes, especially with Async",
    "default": "false",
    "type": "bool"
  },
  {
    "section": "OptiFG",
    "key": "HUDLimit",
    "label": "HUD Limit",
    "description": "Delays HUDless image capture Might cause crashes, especially if set too high!",
    "default": "1",
    "type": "int",
    "min": 1
  },
  {
    "section": "OptiFG",
    "key": "HUDFixExtended",
    "label": "HUD Fix Extended",
    "description": "Extended HUDless checks for more image formats Might cause crash and slowdowns.",
    "default": "false",
    "type": "bool"
  },
  {
    "section": "OptiFG",
    "key": "HudfixDisableRTV",
    "label": "Hudfix Disable RTV",
    "description": "Do not use CreateRenderTargetView for resource tracking",
    "default": "false",
    "type": "bool"
  },
  {
    "section": "OptiFG",
    "key": "HudfixDisableSRV",
    "label": "Hudfix Disable SRV",
    "description": "Do not use CreateShaderResourceView for resource tracking",
    "default": "false",
    "type": "bool"
  },
  {
    "section": "OptiFG",
    "key": "HudfixDisableUAV",
    "label": "Hudfix Disable UAV",
    "description": "Do not use CreateUnorderedAccessView for resource tracking",
    "default": "false",
    "type": "bool"
  },
  {
    "section": "OptiFG",
    "key": "HudfixDisableOM",
    "label": "Hudfix Disable OM",
    "description": "Do not use OMSetRenderTargets for resource tracking",
    "default": "false",
    "type": "bool"
  },
  {
    "section": "OptiFG",
    "key": "HudfixDisableSCR",
    "label": "Hudfix Disable SCR",
    "description": "Do not use SetComputeRootDescriptorTable for resource tracking",
    "default": "true",
    "type": "bool"
  },
  {
    "section": "OptiFG",
    "key": "HudfixDisableSGR",
    "label": "Hudfix Disable SGR",
    "description": "Do not use SetGraphicsRootDescriptorTable for resource tracking",
    "default": "true",
    "type": "bool"
  },
  {
    "section": "OptiFG",
    "key": "HudfixDisableDI",
    "label": "Hudfix Disable DI",
    "description": "Do not use DrawInstanced for resource tracking",
    "default": "false",
    "type": "bool"
  },
  {
    "section": "OptiFG",
    "key": "HudfixDisableDII",
    "label": "Hudfix Disable DII",
    "description": "Do not use DrawIndexedInstanced for resource tracking",
    "default": "false",
    "type": "bool"
  },
  {
    "section": "OptiFG",
    "key": "HudfixDisableDispatch",
    "label": "Hudfix Disable Dispatch",
    "description": "Do not use Dispatch for resource tracking",
    "default": "false",
    "type": "bool"
  },
  {
    "section": "OptiFG",
    "key": "HUDFixDontUseSwapchainBuffers",
    "label": "HUD Fix Dont Use Swapchain Buffers",
    "description": "Prevent swapchain buffers to be used as Hudless Might help fixing overlay issues but also might reduce compatibility",
    "default": "false",
    "type": "bool"
  },
  {
    "section": "OptiFG",
    "key": "HUDFixRelaxedResolutionCheck",
    "label": "HUD Fix Relaxed Resolution Check",
    "description": "Relax resolution checks for Hudless by 32 pixels Helps games which use black borders for some resolutions and screen ratios (e.g. Witcher 3)",
    "default": "false",
    "type": "bool"
  },
  {
    "section": "OptiFG",
    "key": "HUDFixImmediate",
    "label": "HUD Fix Immediate",
    "description": "Enables capturing of resources before shader execution. Increase hudless capture chances but might cause capturing of unnecessary resources.",
    "default": "false",
    "type": "bool"
  },
  {
    "section": "OptiFG",
    "key": "AlwaysTrackHeaps",
    "label": "Always Track Heaps",
    "description": "Resource tracking is always enabled regardless of Hudfix setting Might cause performance issues but disabling might cause stability issues",
    "default": "false",
    "type": "bool"
  },
  {
    "section": "OptiFG",
    "key": "UseShards",
    "label": "Use Shards",
    "description": "Instead of single mutex use shards for tracking resources Might improve performance on heavy multithreaded games",
    "default": "false",
    "type": "bool"
  },
  {
    "section": "OptiFG",
    "key": "ResourceBlocking",
    "label": "Resource Blocking",
    "description": "Block rarely used resources from using as hudless to prevent flickers and other issues",
    "default": "false",
    "type": "bool"
  },
  {
    "section": "OptiFG",
    "key": "MakeDepthCopy",
    "label": "Make Depth Copy",
    "description": "Makes a copy of Depth to be used with Hudfix FG call Setting it false most probably cause occasional garbling",
    "default": "true",
    "type": "bool"
  },
  {
    "section": "OptiFG",
    "key": "EnableDepthScale",
    "label": "Enable Depth Scale",
    "description": "Scale depth buffer according to DepthScaleMax value Fixes broken depth buffer info for DLSS-D + UE",
    "default": "false",
    "type": "bool"
  },
  {
    "section": "OptiFG",
    "key": "DepthScaleMax",
    "label": "Depth Scale Max",
    "description": "Scale value for EnableDepthScale Depth value will be divided to this value",
    "default": "10000.0",
    "type": "float"
  },
  {
    "section": "OptiFG",
    "key": "MakeMVCopy",
    "label": "Make MV Copy",
    "description": "Makes a copy of motion vectors to be used with Hudfix FG call Setting it false most probably cause occasional garbling",
    "default": "true",
    "type": "bool"
  },
  {
    "section": "OptiFG",
    "key": "ResourceFlip",
    "label": "Resource Flip",
    "description": "Flip Depth & Velocity textures This should fix OptiFG issues with Unity games",
    "default": "false",
    "type": "bool"
  },
  {
    "section": "OptiFG",
    "key": "ResourceFlipOffset",
    "label": "Resource Flip Offset",
    "description": "Flip Depth & Velocity textures according to interpolation area This should fix OptiFG issues with Unity games",
    "default": "false",
    "type": "bool"
  },
  {
    "section": "OptiFG",
    "key": "AlwaysCaptureFSRFGSwapchain",
    "label": "Always Capture FSRFG Swapchain",
    "description": "Always captures and swaps FSR-FG 3.1 swapchain with selected output This should fix double present call issue with games create but not use FSR-FG swapchain (Silent Hill f)",
    "default": "false",
    "type": "bool"
  },
  {
    "section": "Inputs",
    "key": "EnableDlssInputs",
    "label": "Enable Dlss Inputs",
    "description": "OptiScaler will hook (nvngx.dll) and use Dlss Inputs",
    "default": "true",
    "type": "bool"
  },
  {
    "section": "Inputs",
    "key": "EnableXeSSInputs",
    "label": "Enable Xe SS Inputs",
    "description": "OptiScaler will hook (libxess.dll) and use XeSS Inputs",
    "default": "true",
    "type": "bool"
  },
  {
    "section": "Inputs",
    "key": "EnableFsr2Inputs",
    "label": "Enable Fsr2 Inputs",
    "description": "OptiScaler will hook Fsr2 Inputs",
    "default": "true",
    "type": "bool"
  },
  {
    "section": "Inputs",
    "key": "UseFsr2Dx11Inputs",
    "label": "Use Fsr2 Dx11 Inputs",
    "description": "OptiScaler will hook Fsr2 Dx11 Inputs instead of Dx12 one",
    "default": "false",
    "type": "bool"
  },
  {
    "section": "Inputs",
    "key": "UseFsr2VulkanInputs",
    "label": "Use Fsr2 Vulkan Inputs",
    "description": "OptiScaler will hook Fsr2 Vulkan Inputs instead of Dx11 & Dx12 ones",
    "default": "false",
    "type": "bool"
  },
  {
    "section": "Inputs",
    "key": "UseFsr2Inputs",
    "label": "Use Fsr2 Inputs",
    "description": "OptiScaler will use Fsr2 Inputs",
    "default": "true",
    "type": "bool"
  },
  {
    "section": "Inputs",
    "key": "Fsr2Pattern",
    "label": "Fsr2 Pattern",
    "description": "Try to find FSR2 methods with pattern matching Will slow down the loading of the game",
    "default": "false",
    "type": "bool"
  },
  {
    "section": "Inputs",
    "key": "EnableFsr3Inputs",
    "label": "Enable Fsr3 Inputs",
    "description": "OptiScaler will hook Fsr3 Inputs",
    "default": "true",
    "type": "bool"
  },
  {
    "section": "Inputs",
    "key": "UseFsr3Inputs",
    "label": "Use Fsr3 Inputs",
    "description": "OptiScaler will use Fsr3 Inputs",
    "default": "true",
    "type": "bool"
  },
  {
    "section": "Inputs",
    "key": "Fsr3Pattern",
    "label": "Fsr3 Pattern",
    "description": "Try to find FSR3 methods with pattern matching Will slow down the loading of the game",
    "default": "false",
    "type": "bool"
  },
  {
    "section": "Inputs",
    "key": "EnableFfxInputs",
    "label": "Enable Ffx Inputs",
    "description": "OptiScaler will hook FidelityFX (amd_fidelityfx_dx12.dll) API Inputs",
    "default": "true",
    "type": "bool"
  },
  {
    "section": "Inputs",
    "key": "UseFfxInputs",
    "label": "Use Ffx Inputs",
    "description": "OptiScaler will use FidelityFX API Inputs",
    "default": "true",
    "type": "bool"
  },
  {
    "section": "Inputs",
    "key": "EnableHotSwapping",
    "label": "Enable Hot Swapping",
    "description": "Enables hot swapping between games FSR3.1 upscaler and OptiScaler's selected upscaler",
    "default": "false",
    "type": "bool"
  },
  {
    "section": "FSRFGInputs",
    "key": "SkipConfigForHudless",
    "label": "Skip Config For Hudless",
    "description": "Do not use Hudless set at ffxConfig",
    "default": "false",
    "type": "bool"
  },
  {
    "section": "FSRFGInputs",
    "key": "SkipDispatchForHudless",
    "label": "Skip Dispatch For Hudless",
    "description": "Do not use Hudless set at ffxDispatch",
    "default": "false",
    "type": "bool"
  },
  {
    "section": "Framerate",
    "key": "FramerateLimit",
    "label": "Framerate Limit",
    "description": "Frame rate limit that uses Reflex, therefore the game has to support Reflex and have it enabled AMD users can use Fakenvapi to get this feature working",
    "default": "0.0",
    "type": "float"
  },
  {
    "section": "XeSS",
    "key": "BuildPipelines",
    "label": "Build Pipelines",
    "description": "Building pipeline for XeSS before init",
    "default": "true",
    "type": "bool"
  },
  {
    "section": "XeSS",
    "key": "CreateHeaps",
    "label": "Create Heaps",
    "description": "Creating heap objects for XeSS before init",
    "default": "false",
    "type": "bool"
  },
  {
    "section": "XeSS",
    "key": "NetworkModel",
    "label": "Network Model",
    "description": "Select XeSS network model Currently doesn't seem to do anything",
    "default": "0",
    "type": "enum",
    "options": [
      "0",
      "1",
      "2",
      "3",
      "4",
      "5"
    ],
    "optionLabels": {
      "0": "KPSS",
      "1": "Splat",
      "2": "Model 3",
      "3": "Model 4",
      "4": "Model 5",
      "5": "Model 6"
    }
  },
  {
    "section": "FSR",
    "key": "VerticalFov",
    "label": "Vertical Fov",
    "description": "Sets camera vertical FOV value for FSR and FSR FG",
    "default": "60.0",
    "type": "float",
    "min": 0.0,
    "max": 180.0
  },
  {
    "section": "FSR",
    "key": "HorizontalFov",
    "label": "Horizontal Fov",
    "description": "If Vertical FOV is not defined will be used to calculate Vertical FOV",
    "default": "off",
    "type": "float",
    "min": 0.0,
    "max": 180.0
  },
  {
    "section": "FSR",
    "key": "CameraNear",
    "label": "Camera Near",
    "description": "Sets camera near value for FSR and FSR FG",
    "default": "0.1",
    "type": "float",
    "min": 0.0
  },
  {
    "section": "FSR",
    "key": "CameraFar",
    "label": "Camera Far",
    "description": "Sets camera far value for FSR and FSR FG",
    "default": "10000.0",
    "type": "float",
    "min": 0.0
  },
  {
    "section": "FSR",
    "key": "UseFsrInputValues",
    "label": "Use Fsr Input Values",
    "description": "Enables usage of camera values (near, far, FOV) received from FSR2/3 or FFX inputs",
    "default": "true",
    "type": "bool"
  },
  {
    "section": "FSR",
    "key": "DebugView",
    "label": "Debug View",
    "description": "Enables Debug View for FSR3.X upscaler",
    "default": "false",
    "type": "bool"
  },
  {
    "section": "FSR",
    "key": "UpscalerIndex",
    "label": "Upscaler Index",
    "description": "Selects upscaler backend for FSR3.X/4",
    "default": "0",
    "type": "enum",
    "options": [
      "0",
      "1",
      "2"
    ],
    "optionLabels": {
      "0": "FSR 4.0.2",
      "1": "FSR 3.1.5",
      "2": "FSR 2.3.4"
    }
  },
  {
    "section": "FSR",
    "key": "FGIndex",
    "label": "FG Index",
    "description": "Selects FG backend for FFX",
    "default": "0",
    "type": "enum",
    "options": [
      "0",
      "1"
    ],
    "optionLabels": {
      "0": "FSR 4.0.0",
      "1": "FSR 3.1.6"
    }
  },
  {
    "section": "FSR",
    "key": "VelocityFactor",
    "label": "Velocity Factor",
    "description": "Sets Velocity Factor for FSR3.1.1 and above Value of 0.0f can improve temporal stability of bright pixels.",
    "default": "1.0",
    "type": "float",
    "min": 0.0,
    "max": 1.0
  },
  {
    "section": "FSR",
    "key": "ReactiveScale",
    "label": "Reactive Scale",
    "description": "Sets Reactiveness Scale for FSR3.1.4 and above Meant for development purpose to test if writing a larger value to reactive mask, reduces ghosting",
    "default": "1.0",
    "type": "float"
  },
  {
    "section": "FSR",
    "key": "ShadingScale",
    "label": "Shading Scale",
    "description": "Sets Shading Scale for FSR3.1.4 and above Increasing this scales fsr3.1 computed shading change value at read to have higher reactiveness.",
    "default": "1.0",
    "type": "float"
  },
  {
    "section": "FSR",
    "key": "AccAddPerFrame",
    "label": "Acc Add Per Frame",
    "description": "Sets Accumulation added per frame for FSR3.1.4 and above Corresponds to amount of accumulation added per frame at pixel coordinate where disocclusion occurred or when reactive mask value is > 0.0f. Decreasing this and drawing the ghosting object (IE no mv) to reactive mask with value close to 1.0f can decrease temporal ghosting. Decreasing this value could result in more thin feature pixels flickering.",
    "default": "0.333",
    "type": "float",
    "min": 0.0,
    "max": 1.0
  },
  {
    "section": "FSR",
    "key": "MinDisOccAcc",
    "label": "Min Dis Occ Acc",
    "description": "Sets Minimum Disocclusion Accumulation for FSR3.1.4 and above Increasing this value may reduce white pixel temporal flickering around swaying thin objects that are disoccluding one another often. Too high value may increase ghosting. A sufficiently negative value means for pixel coordinate at frame N that is disoccluded, add fAccumulationAddedPerFrame starting at frame N+2.",
    "default": "-0.333",
    "type": "float",
    "min": -1.0,
    "max": 1.0
  },
  {
    "section": "FSR",
    "key": "UseReactiveMaskForTransparency",
    "label": "Use Reactive Mask For Transparency",
    "description": "Use raw DLSS reactive mask as transparency mask",
    "default": "true",
    "type": "bool"
  },
  {
    "section": "FSR",
    "key": "DlssReactiveMaskBias",
    "label": "Dlss Reactive Mask Bias",
    "description": "Bias to apply DLSS reactive mask when using with FSR Higher the value, more bias on new frame",
    "default": "0.45",
    "type": "float",
    "min": 0.0,
    "max": 0.9
  },
  {
    "section": "FSR",
    "key": "Fsr4Update",
    "label": "Fsr4 Update",
    "description": "Enables updating of FSR3.X to FSR4",
    "default": "auto",
    "type": "bool"
  },
  {
    "section": "FSR",
    "key": "Fsr4ForceEnableInt8",
    "label": "Fsr4 Force Enable Int8",
    "description": "Enables INT8 model for all GPUs",
    "default": "false",
    "type": "bool"
  },
  {
    "section": "FSR",
    "key": "Fsr4Preset",
    "label": "Fsr4 Preset",
    "description": "Select internal FSR4 preset to use",
    "default": "game's default",
    "type": "enum",
    "options": [
      "0",
      "2"
    ],
    "optionLabels": {
      "0": "For FSR Native AA, 1 = Ultra Quality",
      "2": "Balanced, 3 = Performance, 4 = DRS, 5 = Ultra Performance"
    }
  },
  {
    "section": "FSR",
    "key": "Fsr4EnableDebugView",
    "label": "Fsr4 Enable Debug View",
    "description": "Enable FSR4 Debug View visualization Might consume more VRAM",
    "default": "false",
    "type": "bool"
  },
  {
    "section": "FSR",
    "key": "Fsr4EnableWatermark",
    "label": "Fsr4 Enable Watermark",
    "description": "Enable FSR4 Watermark",
    "default": "false",
    "type": "bool"
  },
  {
    "section": "FSR",
    "key": "Fsr4DoNotLoadAmdxc64",
    "label": "Fsr4 Do Not Load Amdxc64",
    "description": "Prevents OptiScaler from loading amdxc64.dll",
    "default": "false",
    "type": "bool"
  },
  {
    "section": "FSR",
    "key": "FsrNonLinearColorSpace",
    "label": "Fsr Non Linear Color Space",
    "description": "Indicates input color resource uses Non-Linear color space Might improve IQ of FSR4",
    "default": "false",
    "type": "bool"
  },
  {
    "section": "FSR",
    "key": "FsrNonLinearSRGB",
    "label": "Fsr Non Linear SRGB",
    "description": "Indicates input color resource contains perceptual sRGB colors Might improve IQ of FSR4",
    "default": "false",
    "type": "bool"
  },
  {
    "section": "FSR",
    "key": "FsrNonLinearPQ",
    "label": "Fsr Non Linear PQ",
    "description": "Indicates input color resource contains perceptual PQ colors Might improve IQ of FSR4",
    "default": "false",
    "type": "bool"
  },
  {
    "section": "FSR",
    "key": "FsrAgilitySDKUpgrade",
    "label": "Fsr Agility SDK Upgrade",
    "description": "Updates the DirectX 12 Agility SDK Enabling the use of FSR4 on Windows 10 in older titles like Cyberpunk 2077 You MUST copy D3D12_OptiScaler folder next to game's exe!",
    "default": "false",
    "type": "bool"
  },
  {
    "section": "DLSS",
    "key": "Enabled",
    "label": "Enabled",
    "description": "Enables calls to original NVNGX",
    "default": "true",
    "type": "bool"
  },
  {
    "section": "DLSS",
    "key": "RenderPresetOverride",
    "label": "Render Preset Override",
    "description": "Set this to true to enable custom render preset overrides",
    "default": "false",
    "type": "bool"
  },
  {
    "section": "DLSS",
    "key": "RenderPresetForAll",
    "label": "Render Preset For All",
    "description": "Render presets for quality settings Depends on DLSS version, but most recent order is",
    "default": "0",
    "type": "enum",
    "options": [
      "0",
      "1",
      "2",
      "3",
      "4",
      "5",
      "6",
      "7"
    ],
    "optionLabels": {
      "0": "Default",
      "1": "A",
      "2": "B",
      "3": "C",
      "4": "D",
      "5": "E",
      "6": "F",
      "7": "G"
    }
  },
  {
    "section": "DLSS",
    "key": "RenderPresetDLAA",
    "label": "Render Preset DLAA",
    "description": "",
    "type": "enum",
    "options": [
      "0",
      "1",
      "2",
      "3",
      "4",
      "5",
      "6",
      "7"
    ],
    "optionLabels": {
      "0": "Default",
      "1": "A",
      "2": "B",
      "3": "C",
      "4": "D",
      "5": "E",
      "6": "F",
      "7": "G"
    },
    "default": "auto",
    "inheritedFrom": "RenderPresetForAll"
  },
  {
    "section": "DLSS",
    "key": "RenderPresetUltraQuality",
    "label": "Render Preset Ultra Quality",
    "description": "",
    "type": "enum",
    "options": [
      "0",
      "1",
      "2",
      "3",
      "4",
      "5",
      "6",
      "7"
    ],
    "optionLabels": {
      "0": "Default",
      "1": "A",
      "2": "B",
      "3": "C",
      "4": "D",
      "5": "E",
      "6": "F",
      "7": "G"
    },
    "default": "auto",
    "inheritedFrom": "RenderPresetDLAA"
  },
  {
    "section": "DLSS",
    "key": "RenderPresetQuality",
    "label": "Render Preset Quality",
    "description": "",
    "type": "enum",
    "options": [
      "0",
      "1",
      "2",
      "3",
      "4",
      "5",
      "6",
      "7"
    ],
    "optionLabels": {
      "0": "Default",
      "1": "A",
      "2": "B",
      "3": "C",
      "4": "D",
      "5": "E",
      "6": "F",
      "7": "G"
    },
    "default": "auto",
    "inheritedFrom": "RenderPresetUltraQuality"
  },
  {
    "section": "DLSS",
    "key": "RenderPresetBalanced",
    "label": "Render Preset Balanced",
    "description": "",
    "type": "enum",
    "options": [
      "0",
      "1",
      "2",
      "3",
      "4",
      "5",
      "6",
      "7"
    ],
    "optionLabels": {
      "0": "Default",
      "1": "A",
      "2": "B",
      "3": "C",
      "4": "D",
      "5": "E",
      "6": "F",
      "7": "G"
    },
    "default": "auto",
    "inheritedFrom": "RenderPresetQuality"
  },
  {
    "section": "DLSS",
    "key": "RenderPresetPerformance",
    "label": "Render Preset Performance",
    "description": "",
    "type": "enum",
    "options": [
      "0",
      "1",
      "2",
      "3",
      "4",
      "5",
      "6",
      "7"
    ],
    "optionLabels": {
      "0": "Default",
      "1": "A",
      "2": "B",
      "3": "C",
      "4": "D",
      "5": "E",
      "6": "F",
      "7": "G"
    },
    "default": "auto",
    "inheritedFrom": "RenderPresetBalanced"
  },
  {
    "section": "DLSS",
    "key": "RenderPresetUltraPerformance",
    "label": "Render Preset Ultra Performance",
    "description": "",
    "type": "enum",
    "options": [
      "0",
      "1",
      "2",
      "3",
      "4",
      "5",
      "6",
      "7"
    ],
    "optionLabels": {
      "0": "Default",
      "1": "A",
      "2": "B",
      "3": "C",
      "4": "D",
      "5": "E",
      "6": "F",
      "7": "G"
    },
    "default": "auto",
    "inheritedFrom": "RenderPresetPerformance"
  },
  {
    "section": "DLSS",
    "key": "UseGenericAppIdWithDlss",
    "label": "Use Generic App Id With Dlss",
    "description": "Use generic appid with NGX, fixes OptiScaler preset override not working with certain games",
    "default": "false",
    "type": "bool"
  },
  {
    "section": "DLSSD",
    "key": "RenderPresetOverride",
    "label": "Render Preset Override",
    "description": "Set this to true to enable custom render preset overrides",
    "default": "false",
    "type": "bool"
  },
  {
    "section": "DLSSD",
    "key": "RenderPresetForAll",
    "label": "Render Preset For All",
    "description": "Render presets for quality settings Depends on DLSSD version, but most recent order is",
    "default": "0",
    "type": "enum",
    "options": [
      "0",
      "1",
      "2",
      "3",
      "4",
      "5"
    ],
    "optionLabels": {
      "0": "Default",
      "1": "A",
      "2": "B",
      "3": "C",
      "4": "D",
      "5": "E"
    }
  },
  {
    "section": "DLSSD",
    "key": "RenderPresetDLAA",
    "label": "Render Preset DLAA",
    "description": "",
    "type": "enum",
    "options": [
      "0",
      "1",
      "2",
      "3",
      "4",
      "5"
    ],
    "optionLabels": {
      "0": "Default",
      "1": "A",
      "2": "B",
      "3": "C",
      "4": "D",
      "5": "E"
    },
    "default": "auto",
    "inheritedFrom": "RenderPresetForAll"
  },
  {
    "section": "DLSSD",
    "key": "RenderPresetUltraQuality",
    "label": "Render Preset Ultra Quality",
    "description": "",
    "type": "enum",
    "options": [
      "0",
      "1",
      "2",
      "3",
      "4",
      "5"
    ],
    "optionLabels": {
      "0": "Default",
      "1": "A",
      "2": "B",
      "3": "C",
      "4": "D",
      "5": "E"
    },
    "default": "auto",
    "inheritedFrom": "RenderPresetDLAA"
  },
  {
    "section": "DLSSD",
    "key": "RenderPresetQuality",
    "label": "Render Preset Quality",
    "description": "",
    "type": "enum",
    "options": [
      "0",
      "1",
      "2",
      "3",
      "4",
      "5"
    ],
    "optionLabels": {
      "0": "Default",
      "1": "A",
      "2": "B",
      "3": "C",
      "4": "D",
      "5": "E"
    },
    "default": "auto",
    "inheritedFrom": "RenderPresetUltraQuality"
  },
  {
    "section": "DLSSD",
    "key": "RenderPresetBalanced",
    "label": "Render Preset Balanced",
    "description": "",
    "type": "enum",
    "options": [
      "0",
      "1",
      "2",
      "3",
      "4",
      "5"
    ],
    "optionLabels": {
      "0": "Default",
      "1": "A",
      "2": "B",
      "3": "C",
      "4": "D",
      "5": "E"
    },
    "default": "auto",
    "inheritedFrom": "RenderPresetQuality"
  },
  {
    "section": "DLSSD",
    "key": "RenderPresetPerformance",
    "label": "Render Preset Performance",
    "description": "",
    "type": "enum",
    "options": [
      "0",
      "1",
      "2",
      "3",
      "4",
      "5"
    ],
    "optionLabels": {
      "0": "Default",
      "1": "A",
      "2": "B",
      "3": "C",
      "4": "D",
      "5": "E"
    },
    "default": "auto",
    "inheritedFrom": "RenderPresetBalanced"
  },
  {
    "section": "DLSSD",
    "key": "RenderPresetUltraPerformance",
    "label": "Render Preset Ultra Performance",
    "description": "",
    "type": "enum",
    "options": [
      "0",
      "1",
      "2",
      "3",
      "4",
      "5"
    ],
    "optionLabels": {
      "0": "Default",
      "1": "A",
      "2": "B",
      "3": "C",
      "4": "D",
      "5": "E"
    },
    "default": "auto",
    "inheritedFrom": "RenderPresetPerformance"
  },
  {
    "section": "Nukems",
    "key": "MakeDepthCopy",
    "label": "Make Depth Copy",
    "description": "Fix broken visuals in some games (mostly non-UE) on AMD GPUs under Windows Can cause stutters, so best to use only when necessary and mentioned",
    "default": "false",
    "type": "bool"
  },
  {
    "section": "Libraries",
    "key": "OptiDllPath",
    "label": "Opti Dll Path",
    "description": "Main folder for OptiScaler to check dll files below",
    "default": ".\\",
    "type": "string"
  },
  {
    "section": "Libraries",
    "key": "NvngxPath",
    "label": "Nvngx Path",
    "description": "Options below for overriding path per dll nvngx.dll or _nvngx.dll",
    "default": "auto",
    "type": "string"
  },
  {
    "section": "Libraries",
    "key": "NvngxDlssPath",
    "label": "Nvngx Dlss Path",
    "description": "nvngx_dlss.dll",
    "default": "auto",
    "type": "string"
  },
  {
    "section": "Libraries",
    "key": "NvapiPath",
    "label": "Nvapi Path",
    "description": "nvapi64.dll or fakenvapi.dll",
    "default": "auto",
    "type": "string"
  },
  {
    "section": "Libraries",
    "key": "FfxDx12Path",
    "label": "Ffx Dx12 Path",
    "description": "amd_fidelityfx_dx12.dll or amd_fidelityfx_loader_dx12.dll",
    "default": "auto",
    "type": "string"
  },
  {
    "section": "Libraries",
    "key": "FfxDx12SRPath",
    "label": "Ffx Dx12 SR Path",
    "description": "amd_fidelityfx_upscaler_dx12.dll",
    "default": "auto",
    "type": "string"
  },
  {
    "section": "Libraries",
    "key": "FfxDx12FGPath",
    "label": "Ffx Dx12 FG Path",
    "description": "amd_fidelityfx_framegeneration_dx12.dll",
    "default": "auto",
    "type": "string"
  },
  {
    "section": "Libraries",
    "key": "FfxDx12RRPath",
    "label": "Ffx Dx12 RR Path",
    "description": "amd_fidelityfx_denoiser_dx12.dll",
    "default": "auto",
    "type": "string"
  },
  {
    "section": "Libraries",
    "key": "FfxDx12RCPath",
    "label": "Ffx Dx12 RC Path",
    "description": "amd_fidelityfx_radiancecache_dx12.dll",
    "default": "auto",
    "type": "string"
  },
  {
    "section": "Libraries",
    "key": "FfxVkPath",
    "label": "Ffx Vk Path",
    "description": "amd_fidelityfx_vk.dll",
    "default": "auto",
    "type": "string"
  },
  {
    "section": "Libraries",
    "key": "XeSSPath",
    "label": "Xe SS Path",
    "description": "libxess.dll",
    "default": "auto",
    "type": "string"
  },
  {
    "section": "Libraries",
    "key": "XeFGPath",
    "label": "Xe FG Path",
    "description": "libxess_fg.dll",
    "default": "auto",
    "type": "string"
  },
  {
    "section": "Libraries",
    "key": "XeLLPath",
    "label": "Xe LL Path",
    "description": "libxell.dll",
    "default": "auto",
    "type": "string"
  },
  {
    "section": "Libraries",
    "key": "XeSSDx11Path",
    "label": "Xe SS Dx11 Path",
    "description": "libxess_dx11.dll",
    "default": "auto",
    "type": "string"
  },
  {
    "section": "Libraries",
    "key": "NvngxFeaturePath",
    "label": "Nvngx Feature Path",
    "description": "This path will be added to paths of Nvngx during init",
    "default": "auto",
    "type": "string"
  },
  {
    "section": "Menu",
    "key": "OverlayMenu",
    "label": "Overlay Menu",
    "description": "Enables new Overlay ImGui menus without this option OptiScaler will disable all FG features",
    "default": "when OptiScaler is nvngx.dll false otherwise true",
    "type": "bool"
  },
  {
    "section": "Menu",
    "key": "Scale",
    "label": "Scale",
    "description": "In-game ImGui menu scale",
    "default": "1.0",
    "type": "float",
    "min": 0.5,
    "max": 2.0
  },
  {
    "section": "Menu",
    "key": "ShortcutKey",
    "label": "Shortcut Key",
    "description": "Shortcut key for opening menu For all keycode values, you can check this address Match Description with key Value https://learn.microsoft.com/en-us/windows/win32/inputdev/virtual-key-codes Integer value - Default (auto) is 0x2D which equals VK_INSERT/Insert key, previous default key was 0x24 -> VK_HOME/Home key If you want to use e.g. VK_BACK/Backspace key, that would be 0x08 - set ShortcutKey=0x08",
    "default": "auto",
    "type": "keycode"
  },
  {
    "section": "Menu",
    "key": "ExtendedLimits",
    "label": "Extended Limits",
    "description": "Extends Scaling Ratio limits to 0.1 - 6.0",
    "default": "false",
    "type": "bool"
  },
  {
    "section": "Menu",
    "key": "UseHQFont",
    "label": "Use HQ Font",
    "description": "Use High Quality Font for Menu Might use more VRAM If you see a black overlay or experience menu related crashes with Vulkan, try disabling",
    "default": "true",
    "type": "bool"
  },
  {
    "section": "Menu",
    "key": "FontSize",
    "label": "Font Size",
    "description": "Controls the size of just the font without touching other style elements Mostly useful when using custom fonts via TTFFontPath",
    "default": "14.0",
    "type": "float"
  },
  {
    "section": "Menu",
    "key": "TTFFontPath",
    "label": "TTF Font Path",
    "description": "Path to a font to be used as HQ Font, requires UseHQFont=true Best to use monospace fonts Example path: C:\\\\Windows\\\\Fonts\\\\comic.ttf",
    "default": "Hack-Regular bundled with OptiScaler",
    "type": "string"
  },
  {
    "section": "Menu",
    "key": "DisableSplash",
    "label": "Disable Splash",
    "description": "Disables Startup Splash message",
    "default": "false",
    "type": "bool"
  },
  {
    "section": "Menu",
    "key": "ShowFps",
    "label": "Show Fps",
    "description": "Enables FPS overlay",
    "default": "false",
    "type": "bool"
  },
  {
    "section": "Menu",
    "key": "FpsScale",
    "label": "Fps Scale",
    "description": "In-game FPS Overlay scale",
    "default": "using the same scale as menu",
    "type": "float",
    "min": 0.5,
    "max": 2.0
  },
  {
    "section": "Menu",
    "key": "FpsOverlayPos",
    "label": "Fps Overlay Pos",
    "description": "FPS overlay position",
    "default": "0",
    "type": "enum",
    "options": [
      "0",
      "1",
      "2"
    ],
    "optionLabels": {
      "0": "Top Left",
      "1": "Top Right",
      "2": "Bottom Left"
    }
  },
  {
    "section": "Menu",
    "key": "FpsOverlayType",
    "label": "Fps Overlay Type",
    "description": "FPS overlay type",
    "default": "0",
    "type": "enum",
    "options": [
      "0",
      "1",
      "2",
      "3"
    ],
    "optionLabels": {
      "0": "Just FPS",
      "1": "Simple",
      "2": "Detailed",
      "3": "Detailed + Graph"
    }
  },
  {
    "section": "Menu",
    "key": "FpsShortcutKey",
    "label": "Fps Shortcut Key",
    "description": "Shortcut key for FPS overlay https://learn.microsoft.com/en-us/windows/win32/inputdev/virtual-key-codes Integer value - Default (auto) is 0x21 -> VK_PRIOR/Page up key",
    "default": "auto",
    "type": "keycode"
  },
  {
    "section": "Menu",
    "key": "FpsCycleShortcutKey",
    "label": "Fps Cycle Shortcut Key",
    "description": "Shortcut key for FPS overlay type cycle https://learn.microsoft.com/en-us/windows/win32/inputdev/virtual-key-codes Integer value - Default (auto) is 0x22 -> VK_NEXT/Page down key",
    "default": "auto",
    "type": "keycode"
  },
  {
    "section": "Menu",
    "key": "FpsOverlayHorizontal",
    "label": "Fps Overlay Horizontal",
    "description": "Enables Horizontal FPS overlay layout",
    "default": "false",
    "type": "bool"
  },
  {
    "section": "Menu",
    "key": "FpsOverlayAlpha",
    "label": "Fps Overlay Alpha",
    "description": "FPS Overlay background alpha",
    "default": "0.4",
    "type": "float",
    "min": 0.0,
    "max": 1.0
  },
  {
    "section": "Menu",
    "key": "FGShortcutKey",
    "label": "FG Shortcut Key",
    "description": "Shortcut key for FG enabled/disabled https://learn.microsoft.com/en-us/windows/win32/inputdev/virtual-key-codes Integer value - Default (auto) is 0x23 -> VK_END/End key",
    "default": "auto",
    "type": "keycode"
  },
  {
    "section": "Menu",
    "key": "LightTheme",
    "label": "Light Theme",
    "description": "Enables Light Theme for Menu",
    "default": "false",
    "type": "bool"
  },
  {
    "section": "Menu",
    "key": "AccentColorR",
    "label": "Accent Color R",
    "description": "Accent color for the menu R/G/B float colors values of the accent color for the menu 0.0 to 1.0 - Default (auto) R: 0.0, G: 0.4, B: 0.77 (Blue)",
    "default": "auto",
    "type": "string"
  },
  {
    "section": "Menu",
    "key": "AccentColorG",
    "label": "Accent Color G",
    "description": "",
    "type": "string",
    "default": "auto",
    "inheritedFrom": "AccentColorR"
  },
  {
    "section": "Menu",
    "key": "AccentColorB",
    "label": "Accent Color B",
    "description": "",
    "type": "string",
    "default": "auto",
    "inheritedFrom": "AccentColorG"
  },
  {
    "section": "Menu",
    "key": "BGColorR",
    "label": "BG Color R",
    "description": "Background color for the menu R/G/B float colors values of the accent color for the menu 0.0 to 1.0 - Default (auto) R: 0.0, G: 0.0, B: 0.0 (Black)",
    "default": "auto",
    "type": "string"
  },
  {
    "section": "Menu",
    "key": "BGColorG",
    "label": "BG Color G",
    "description": "",
    "type": "string",
    "default": "auto",
    "inheritedFrom": "BGColorR"
  },
  {
    "section": "Menu",
    "key": "BGColorB",
    "label": "BG Color B",
    "description": "",
    "type": "string",
    "default": "auto",
    "inheritedFrom": "BGColorG"
  },
  {
    "section": "Menu",
    "key": "BGColorA",
    "label": "BG Color A",
    "description": "Background alpha for the menu 0 is transparent and 1 is opaque 0.0 to 1.0 - Default (auto) 0.99",
    "default": "auto",
    "type": "string"
  },
  {
    "section": "Spoofing",
    "key": "SpoofedVendorId",
    "label": "Spoofed Vendor Id",
    "description": "VendorID to spoof",
    "default": "0x10de",
    "type": "enum",
    "options": [
      "8086",
      "1002"
    ],
    "optionLabels": {
      "8086": "Intel",
      "1002": "AMD"
    }
  },
  {
    "section": "Spoofing",
    "key": "SpoofedDeviceId",
    "label": "Spoofed Device Id",
    "description": "DeviceID to spoof 0x2684 = 4090 | 0xE20B = B580 | 0x7550 9070 XT",
    "default": "0x2684 (4090)",
    "type": "int"
  },
  {
    "section": "Spoofing",
    "key": "TargetVendorId",
    "label": "Target Vendor Id",
    "description": "Target VendorID to be spoofed",
    "default": "all",
    "type": "int"
  },
  {
    "section": "Spoofing",
    "key": "TargetDeviceId",
    "label": "Target Device Id",
    "description": "Target DeviceID to be spoofed",
    "default": "all",
    "type": "string"
  },
  {
    "section": "Spoofing",
    "key": "SpoofedGPUName",
    "label": "Spoofed GPU Name",
    "description": "Spoofed GPU name NVIDIA GeForce RTX 4090 | Intel(R) Arc(TM) B580 Graphics | AMD Radeon RX 9070 XT",
    "default": "NVIDIA GeForce RTX 4090",
    "type": "string"
  },
  {
    "section": "Spoofing",
    "key": "StreamlineSpoofing",
    "label": "Streamline Spoofing",
    "description": "Enables GPU spoofing for Streamline, even if Dxgi spoofing is disabled for the rest of the game Usually allows for using Fakenvapi without spoofing the whole game, and sometimes DLSS/DLSSG",
    "default": "true",
    "type": "bool"
  },
  {
    "section": "Spoofing",
    "key": "Dxgi",
    "label": "Dxgi",
    "description": "Enables Nvidia GPU spoofing for DXGI (can be changed above to spoof other vendors)",
    "default": "true",
    "type": "bool"
  },
  {
    "section": "Spoofing",
    "key": "DxgiFactoryWrapping",
    "label": "Dxgi Factory Wrapping",
    "description": "Enables wrapping of DxgiFactory instead of hooking Might cause issues or help Nvidia cards with other mods",
    "default": "false",
    "type": "bool"
  },
  {
    "section": "Spoofing",
    "key": "DxgiBlacklist",
    "label": "Dxgi Blacklist",
    "description": "Skips DXGI GPU spoofing when caller method in the list (example: slInit|slGetPluginFunction|nvapi_QueryInterface) Be careful this will disable spoofing for rest of the calls, also does not work on Linux",
    "default": "disabled",
    "type": "string"
  },
  {
    "section": "Spoofing",
    "key": "DxgiVRAM",
    "label": "Dxgi VRAM",
    "description": "Spoof amount of VRAM for DXGI",
    "default": "disabled",
    "type": "string"
  },
  {
    "section": "Spoofing",
    "key": "Vulkan",
    "label": "Vulkan",
    "description": "Enables Nvidia GPU spoofing for Vulkan (can be changed above to spoof other vendors)",
    "default": "false",
    "type": "bool"
  },
  {
    "section": "Spoofing",
    "key": "VulkanExtensionSpoofing",
    "label": "Vulkan Extension Spoofing",
    "description": "Enables Nvidia extension spoofing for Vulkan",
    "default": "false",
    "type": "bool"
  },
  {
    "section": "Spoofing",
    "key": "VulkanVRAM",
    "label": "Vulkan VRAM",
    "description": "Spoof amount of VRAM for Vulkan",
    "default": "disabled",
    "type": "string"
  },
  {
    "section": "Spoofing",
    "key": "SpoofHAGS",
    "label": "Spoof HAGS",
    "description": "Enables spoofing of Hardware Accelerated GPU Scheduling Required for Nukem's mod, also lets RTX40xx series users use DLSSG without HAGS enabled",
    "default": "false",
    "type": "bool"
  },
  {
    "section": "Spoofing",
    "key": "D3DFeatureLevel",
    "label": "D3 D Feature Level",
    "description": "Enables overriding of requested D3D feature level",
    "default": "false",
    "type": "bool"
  },
  {
    "section": "Spoofing",
    "key": "UEIntelAtomics",
    "label": "UE Intel Atomics",
    "description": "Prevents DirectX12 not supported error on UE games with Intel cards when spoofing enabled",
    "default": "false",
    "type": "bool"
  },
  {
    "section": "Spoofing",
    "key": "Registry",
    "label": "Registry",
    "description": "Spoofs Vendor ID, Device ID and Driver Version at registry level",
    "default": "false",
    "type": "bool"
  },
  {
    "section": "Spoofing",
    "key": "RegistryDriver",
    "label": "Registry Driver",
    "description": "Driver version to be spoofed at registry",
    "default": "32.0.15.9155 (For Nvidia)",
    "type": "string"
  },
  {
    "section": "Spoofing",
    "key": "User32",
    "label": "User32",
    "description": "Spoofs Vendor ID, Device ID at User32 level",
    "default": "false",
    "type": "bool"
  },
  {
    "section": "Plugins",
    "key": "Path",
    "label": "Path",
    "description": "Path that will be searched for same filename plugins (dxgi.dll, winmm.dll, etc.)",
    "default": "plugins under OptiDllPath \".\\OptiScaler\\plugins\\\"",
    "type": "string"
  },
  {
    "section": "Plugins",
    "key": "LoadAsiPlugins",
    "label": "Load Asi Plugins",
    "description": "Lets OptiScaler load *.asi files in plugins folder",
    "default": "false",
    "type": "bool"
  },
  {
    "section": "Plugins",
    "key": "LateAsiPluginsDelay",
    "label": "Late Asi Plugins Delay",
    "description": "Delay before injecting late-loaded *.asi files in plugins folder To load an ASI plugin late, add -loadlate to its filename before the extension, e.g. \"myplugin-loadlate.asi\"",
    "default": "30",
    "type": "int"
  },
  {
    "section": "Plugins",
    "key": "LoadSpecialK",
    "label": "Load Special K",
    "description": "Loads SpecialK64.dll from game's exe folder Please create an empty SpecialK.dxgi file next to SpecialK64.dll to set SpecialK's working mode, otherwise it will not be activated BECAUSE OF STABILITY ISSUES, WILL NOT BE LOADED WHEN OPTIFG, DLSSG via SL or FSR-FG INPUTS ARE ENABLED",
    "default": "false",
    "type": "bool"
  },
  {
    "section": "Plugins",
    "key": "LoadReshade",
    "label": "Load Reshade",
    "description": "Loads Reshade64.dll from game's exe folder Rename Reshade dll to ReShade64.dll, put next to OptiScaler and set to true",
    "default": "false",
    "type": "bool"
  },
  {
    "section": "NvApi",
    "key": "OverrideNvapiDll",
    "label": "Override Nvapi Dll",
    "description": "Override loading of nvapi64.dll",
    "default": "false",
    "type": "bool"
  },
  {
    "section": "NvApi",
    "key": "DisableFlipMetering",
    "label": "Disable Flip Metering",
    "description": "Disable FlipMetering Fix the thick frametime graph caused by Nvidia's Flip Metering when using NukemFG, needs Fakenvapi to work",
    "default": "false",
    "type": "bool"
  },
  {
    "section": "NvApi",
    "key": "DontUseFakenvapiForXeLLOnNvidia",
    "label": "Dont Use Fakenvapi For Xe LL On Nvidia",
    "description": "Do not use fakenvapi for converting Reflex calls to XeLL calls on Nvidia GPUs",
    "default": "false",
    "type": "bool"
  },
  {
    "section": "Dx11withDx12",
    "key": "UseDelayedInit",
    "label": "Use Delayed Init",
    "description": "Delay some operations during creation of D11wDx12 features to increase compatibility",
    "default": "false",
    "type": "bool"
  },
  {
    "section": "Dx11withDx12",
    "key": "DontUseNTShared",
    "label": "Dont Use NT Shared",
    "description": "Prefer using D3D11_RESOURCE_MISC_SHARED, which is lower level and a bit more performant and possibly less compatible",
    "default": "true",
    "type": "bool"
  },
  {
    "section": "Hooks",
    "key": "EarlyHooking",
    "label": "Early Hooking",
    "description": "Early hooking of kernel methods May cause compatibility issues!!!",
    "default": "false",
    "type": "bool"
  },
  {
    "section": "Hooks",
    "key": "HookOriginalNvngxOnly",
    "label": "Hook Original Nvngx Only",
    "description": "Skip hooking of local nvngx files and only hook nvngx at registry Needed for Uniscaler + FG",
    "default": "false",
    "type": "bool"
  },
  {
    "section": "Hooks",
    "key": "UseNtdllHooks",
    "label": "Use Ntdll Hooks",
    "description": "Only hook ntdll.dll methods, skip kernel32.dll and kernelbase.dll hooks",
    "default": "true",
    "type": "bool"
  },
  {
    "section": "Sharpness",
    "key": "OverrideSharpness",
    "label": "Override Sharpness",
    "description": "Override DLSS Sharpness parameter with fixed Sharpness value",
    "default": "false",
    "type": "bool"
  },
  {
    "section": "Sharpness",
    "key": "Sharpness",
    "label": "Sharpness",
    "description": "Strength of Sharpening,",
    "default": "0.3",
    "type": "float",
    "min": 0.0,
    "max": 1.0
  },
  {
    "section": "OutputScaling",
    "key": "Enabled",
    "label": "Enabled",
    "description": "Enable Output Scaling option for Dx12 and Dx11 with Dx12 backends",
    "default": "false",
    "type": "bool"
  },
  {
    "section": "OutputScaling",
    "key": "Multiplier",
    "label": "Multiplier",
    "description": "Output Scaling ratio",
    "default": "1.5",
    "type": "float",
    "min": 0.5,
    "max": 3.0
  },
  {
    "section": "OutputScaling",
    "key": "Downscaler",
    "label": "Downscaler",
    "description": "Downscaler to use for Output Scaling",
    "default": "0",
    "type": "enum",
    "options": [
      "0",
      "1",
      "2",
      "3",
      "4",
      "5",
      "6",
      "7"
    ],
    "optionLabels": {
      "0": "FSR1",
      "1": "Bicubic",
      "2": "Catmull-Rom",
      "3": "Lanczos2",
      "4": "Lanczos3",
      "5": "Kaiser2",
      "6": "Kaiser3",
      "7": "MAGIC"
    }
  },
  {
    "section": "CAS",
    "key": "Enabled",
    "label": "Enabled",
    "description": "Enables RCAS sharpening",
    "default": "false",
    "type": "bool"
  },
  {
    "section": "CAS",
    "key": "MotionSharpnessEnabled",
    "label": "Motion Sharpness Enabled",
    "description": "Enable Motion Sharpness",
    "default": "false",
    "type": "bool"
  },
  {
    "section": "CAS",
    "key": "MotionSharpness",
    "label": "Motion Sharpness",
    "description": "Sharpening will be added or removed according to motion length",
    "default": "0.4",
    "type": "float",
    "min": -1.3,
    "max": 1.3
  },
  {
    "section": "CAS",
    "key": "MotionThreshold",
    "label": "Motion Threshold",
    "description": "How much a pixel should move before Motion Sharpness is applied",
    "default": "0.0",
    "type": "float",
    "min": 0.0,
    "max": 100.0
  },
  {
    "section": "CAS",
    "key": "MotionScaleLimit",
    "label": "Motion Scale Limit",
    "description": "How much a pixel should move to reach maximum MotionSharpness value Values between MotionThreshold and this value will use be used to scale sharpness value",
    "default": "10.0",
    "type": "float",
    "min": 0.0,
    "max": 100.0
  },
  {
    "section": "CAS",
    "key": "ContrastEnabled",
    "label": "Contrast Enabled",
    "description": "Enable Contrast based sharpening Increases sharpness at high contrast areas.",
    "default": "false",
    "type": "bool"
  },
  {
    "section": "CAS",
    "key": "Contrast",
    "label": "Contrast",
    "description": "Contrast based sharpening value Higher values increases sharpness at high contrast areas. High values might cause graphical GLITCHES when used with high sharpness values !!!",
    "default": "-0.3",
    "type": "float",
    "min": -2.0,
    "max": 2.0
  },
  {
    "section": "CAS",
    "key": "SharpenerDebug",
    "label": "Sharpener Debug",
    "description": "Enable Debug Highlighting for Motion/DA Sharpening Reddish hue for added, greenish for reduced sharpness Blue tint for detected edges in Depth Aware sharpening",
    "default": "false",
    "type": "bool"
  },
  {
    "section": "CAS",
    "key": "UseDepthAwareSharpen",
    "label": "Use Depth Aware Sharpen",
    "description": "Enables Depth-Aware RCAS sharpening. Reduces sharpening across object boundaries to prevent halos and artifacts. The farther away is the object, the more sharpening is applied (limited to 1.0) Recommended for scenes with complex geometry or upscaling.",
    "default": "false",
    "type": "bool"
  },
  {
    "section": "CAS",
    "key": "UseDASDepthAwareSharpen",
    "label": "Use DAS Depth Aware Sharpen",
    "description": "Enables Depth-Aware Directional Adaptive Sharpening (DAS). Reduces sharpening across object boundaries to prevent halos and artifacts. The farther away is the object, the more sharpening is applied (limited to 1.0) Recommended for scenes with complex geometry or upscaling.",
    "default": "false",
    "type": "bool"
  },
  {
    "section": "CAS",
    "key": "DADepthIsLinear",
    "label": "DA Depth Is Linear",
    "description": "Indicates whether the input depth is already linear. Enable if depth represents real distance (linear space). Disable if using hardware depth (non-linear), which will be linearized in the shader. Incorrect setting will cause broken edge detection.",
    "default": "false",
    "type": "bool"
  },
  {
    "section": "CAS",
    "key": "DADepthScale",
    "label": "DA Depth Scale",
    "description": "Controls how strongly sharpening is reduced across depth edges. Higher values more aggressively block sharpening at object boundaries (reduces halos). Lower values allow more sharpening across edges (sharper, but riskier).",
    "default": "4.0",
    "type": "float",
    "min": 2.0,
    "max": 600.0
  },
  {
    "section": "CAS",
    "key": "DADepthBias",
    "label": "DA Depth Bias",
    "description": "Ignores small depth differences before edge detection. Higher values reduce noise and flickering from minor depth changes. Lower values preserve fine detail, but may react to depth noise.",
    "default": "0.01",
    "type": "float",
    "min": 0.005,
    "max": 0.03
  },
  {
    "section": "CAS",
    "key": "DAClampOutput",
    "label": "DA Clamp Output",
    "description": "Clamps the final image to the [0, 1] range. Prevents overshoot artifacts such as bright halos or negative colors. Recommended for LDR pipelines; optional for HDR depending on tone-mapping.",
    "default": "false",
    "type": "bool"
  },
  {
    "section": "Log",
    "key": "LogToFile",
    "label": "Log To File",
    "description": "Should a log file be created",
    "default": "false",
    "type": "bool"
  },
  {
    "section": "Log",
    "key": "LogLevel",
    "label": "Log Level",
    "description": "Verbosity level of file logs",
    "default": "0",
    "type": "enum",
    "options": [
      "0",
      "1",
      "2",
      "3",
      "4"
    ],
    "optionLabels": {
      "0": "Trace",
      "1": "Debug",
      "2": "Info",
      "3": "Warning",
      "4": "Error"
    }
  },
  {
    "section": "Log",
    "key": "LogToConsole",
    "label": "Log To Console",
    "description": "Log to console (Log level is always 2 (Info) for performance reasons)",
    "default": "false",
    "type": "bool"
  },
  {
    "section": "Log",
    "key": "LogToNGX",
    "label": "Log To NGX",
    "description": "Log to NVNGX API",
    "default": "false",
    "type": "bool"
  },
  {
    "section": "Log",
    "key": "LogToDebug",
    "label": "Log To Debug",
    "description": "Log to Debug output",
    "default": "false",
    "type": "bool"
  },
  {
    "section": "Log",
    "key": "OpenConsole",
    "label": "Open Console",
    "description": "Open console window for logs",
    "default": "false",
    "type": "bool"
  },
  {
    "section": "Log",
    "key": "SingleFile",
    "label": "Single File",
    "description": "When set to false creates a new log file for every OptiScaler session",
    "default": "true",
    "type": "bool"
  },
  {
    "section": "Log",
    "key": "LogFileName",
    "label": "Log File Name",
    "description": "Custom log filename You can also specify a custom *path* for the log",
    "default": "OptiScaler.log in current folder",
    "type": "string"
  },
  {
    "section": "Log",
    "key": "LogAsync",
    "label": "Log Async",
    "description": "Enables Async logging",
    "default": "true",
    "type": "bool"
  },
  {
    "section": "Log",
    "key": "LogAsyncThreads",
    "label": "Log Async Threads",
    "description": "Async logging threads",
    "default": "1",
    "type": "int",
    "min": 1,
    "max": 8
  },
  {
    "section": "InitFlags",
    "key": "AutoExposure",
    "label": "Auto Exposure",
    "description": "Force add ENABLE_AUTOEXPOSURE to init flags Some Unreal Engine games need this, fixes colors specially in dark areas",
    "default": "DLSS value",
    "type": "bool"
  },
  {
    "section": "InitFlags",
    "key": "HDR",
    "label": "HDR",
    "description": "Force add HDR_INPUT_COLOR to init flags",
    "default": "DLSS value",
    "type": "bool"
  },
  {
    "section": "InitFlags",
    "key": "DepthInverted",
    "label": "Depth Inverted",
    "description": "Force add INVERTED_DEPTH to init flags",
    "default": "DLSS value",
    "type": "bool"
  },
  {
    "section": "InitFlags",
    "key": "JitterCancellation",
    "label": "Jitter Cancellation",
    "description": "Force add JITTERED_MV flag to init flags",
    "default": "DLSS value",
    "type": "bool"
  },
  {
    "section": "InitFlags",
    "key": "DisplayResolution",
    "label": "Display Resolution",
    "description": "Force add HIGH_RES_MV flag to init flags",
    "default": "DLSS value",
    "type": "bool"
  },
  {
    "section": "InitFlags",
    "key": "DisableReactiveMask",
    "label": "Disable Reactive Mask",
    "description": "Force remove RESPONSIVE_PIXEL_MASK from init flags",
    "default": "true",
    "type": "bool"
  },
  {
    "section": "UpscaleRatio",
    "key": "UpscaleRatioOverrideEnabled",
    "label": "Upscale Ratio Override Enabled",
    "description": "Set this to true to enable the internal Resolution Override",
    "default": "false",
    "type": "bool"
  },
  {
    "section": "UpscaleRatio",
    "key": "UpscaleRatioOverrideValue",
    "label": "Upscale Ratio Override Value",
    "description": "Set the forced Upscale Ratio value",
    "default": "1.3",
    "type": "string"
  },
  {
    "section": "QualityOverrides",
    "key": "QualityRatioOverrideEnabled",
    "label": "Quality Ratio Override Enabled",
    "description": "Set this to true to enable Custom quality mode overrides",
    "default": "false",
    "type": "bool"
  },
  {
    "section": "QualityOverrides",
    "key": "QualityRatioDLAA",
    "label": "Quality Ratio DLAA",
    "description": "Set Custom Upscaling Ratio for each quality mode Default (auto) values: DLAA\t\t\t\t\t: 1.0 Ultra Quality         : 1.3 Quality               : 1.5 Balanced              : 1.7 Performance           : 2.0 Ultra Performance     : 3.0",
    "default": "auto",
    "type": "string"
  },
  {
    "section": "QualityOverrides",
    "key": "QualityRatioUltraQuality",
    "label": "Quality Ratio Ultra Quality",
    "description": "",
    "type": "string",
    "default": "auto",
    "inheritedFrom": "QualityRatioDLAA"
  },
  {
    "section": "QualityOverrides",
    "key": "QualityRatioQuality",
    "label": "Quality Ratio Quality",
    "description": "",
    "type": "string",
    "default": "auto",
    "inheritedFrom": "QualityRatioUltraQuality"
  },
  {
    "section": "QualityOverrides",
    "key": "QualityRatioBalanced",
    "label": "Quality Ratio Balanced",
    "description": "",
    "type": "string",
    "default": "auto",
    "inheritedFrom": "QualityRatioQuality"
  },
  {
    "section": "QualityOverrides",
    "key": "QualityRatioPerformance",
    "label": "Quality Ratio Performance",
    "description": "",
    "type": "string",
    "default": "auto",
    "inheritedFrom": "QualityRatioBalanced"
  },
  {
    "section": "QualityOverrides",
    "key": "QualityRatioUltraPerformance",
    "label": "Quality Ratio Ultra Performance",
    "description": "",
    "type": "string",
    "default": "auto",
    "inheritedFrom": "QualityRatioPerformance"
  },
  {
    "section": "DRS",
    "key": "DrsMinOverrideEnabled",
    "label": "Drs Min Override Enabled",
    "description": "Set this to true to enable limiting DRS min resolution to Rendering resolution",
    "default": "false",
    "type": "bool"
  },
  {
    "section": "DRS",
    "key": "DrsMaxOverrideEnabled",
    "label": "Drs Max Override Enabled",
    "description": "Set this to true to enable limiting DRS max resolution to Rendering resolution",
    "default": "false",
    "type": "bool"
  },
  {
    "section": "HDR",
    "key": "ForceHDR",
    "label": "Force HDR",
    "description": "Force HDR color space",
    "default": "false",
    "type": "bool"
  },
  {
    "section": "HDR",
    "key": "UseHDR10",
    "label": "Use HDR10",
    "description": "Use HDR10 DXGI_FORMAT_R10G10B10A2_UNORM instead of DXGI_FORMAT_R16G16B16A16_FLOAT",
    "default": "false",
    "type": "bool"
  },
  {
    "section": "HDR",
    "key": "SkipColorSpace",
    "label": "Skip Color Space",
    "description": "Skip setting HDR colorspace",
    "default": "false",
    "type": "bool"
  },
  {
    "section": "V-Sync",
    "key": "OverrideVsync",
    "label": "Override Vsync",
    "description": "Enable V-Sync controls",
    "default": "false",
    "type": "bool"
  },
  {
    "section": "V-Sync",
    "key": "ForceVsync",
    "label": "Force Vsync",
    "description": "Force V-Sync value",
    "default": "none selected",
    "type": "bool"
  },
  {
    "section": "V-Sync",
    "key": "SyncInterval",
    "label": "Sync Interval",
    "description": "Sync interval value for V-Sync",
    "default": "none selected",
    "type": "int",
    "min": 0,
    "max": 3
  },
  {
    "section": "Anisotropy",
    "key": "AnisotropyOverride",
    "label": "Anisotropy Override",
    "description": "Override max Anisotropy/Anisotropic Filtering for textures",
    "default": "disabled",
    "type": "enum",
    "options": [
      "2",
      "4",
      "8",
      "16"
    ]
  },
  {
    "section": "Anisotropy",
    "key": "ModifyComparison",
    "label": "Modify Comparison",
    "description": "Change comparison filters to Anisotropic ones",
    "default": "true",
    "type": "bool"
  },
  {
    "section": "Anisotropy",
    "key": "ModifyMinMax",
    "label": "Modify Min Max",
    "description": "Change min/max filters to Anisotropic ones",
    "default": "true",
    "type": "bool"
  },
  {
    "section": "Anisotropy",
    "key": "SkipPointFilter",
    "label": "Skip Point Filter",
    "description": "Skip overriding on point filters",
    "default": "true",
    "type": "bool"
  },
  {
    "section": "Mipmap",
    "key": "MipmapBiasOverride",
    "label": "Mipmap Bias Override",
    "description": "Override value for Mipmap LOD bias",
    "default": "disabled",
    "type": "float",
    "min": -15.0,
    "max": 15.0
  },
  {
    "section": "Mipmap",
    "key": "MipmapBiasFixedOverride",
    "label": "Mipmap Bias Fixed Override",
    "description": "Use a fixed value for LOD bias",
    "default": "false",
    "type": "bool"
  },
  {
    "section": "Mipmap",
    "key": "MipmapBiasScaleOverride",
    "label": "Mipmap Bias Scale Override",
    "description": "Use override value as scale multiplier",
    "default": "false",
    "type": "bool"
  },
  {
    "section": "Mipmap",
    "key": "MipmapBiasOverrideAll",
    "label": "Mipmap Bias Override All",
    "description": "Override all textures LOD bias (normally only overriding < 0 values)",
    "default": "false",
    "type": "bool"
  },
  {
    "section": "ProcessFilter",
    "key": "TargetProcessName",
    "label": "Target Process Name",
    "description": "Only inject into this specific process (case-insensitive) Example: TargetProcessName=endfield.exe",
    "default": "disabled",
    "type": "string"
  },
  {
    "section": "ProcessFilter",
    "key": "ProcessExclusionList",
    "label": "Process Exclusion List",
    "description": "Don't inject into this specific process (case-insensitive) Process names seperated with pipe \"|\" - Default (auto) is crashpad_handler.exe and others - listed in Config.h under ProcessFilter",
    "default": "auto",
    "type": "string"
  },
  {
    "section": "Hotfix",
    "key": "CheckForUpdate",
    "label": "Check For Update",
    "description": "Enables checking for latest version from Github",
    "default": "true",
    "type": "bool"
  },
  {
    "section": "Hotfix",
    "key": "DisableOverlays",
    "label": "Disable Overlays",
    "description": "Enables blocking of Steam and Epic overlays Also blocks Steam Input",
    "default": "false",
    "type": "bool"
  },
  {
    "section": "Hotfix",
    "key": "ManualInputPolling",
    "label": "Manual Input Polling",
    "description": "Use manual input polling instead of hooking WndProc Might help games which does not capture inputs properly As a downside it will not be able to block inputs when menu is open",
    "default": "false",
    "type": "bool"
  },
  {
    "section": "Hotfix",
    "key": "SimulateWaitableObject",
    "label": "Simulate Waitable Object",
    "description": "Simulate waitable object event signals for FG swapchain",
    "default": "false",
    "type": "bool"
  },
  {
    "section": "Hotfix",
    "key": "CreateD3D12DeviceForLuma",
    "label": "Create D3 D12 Device For Luma",
    "description": "OptiScaler will delay loading of Reshade and create D3D12 device first This option will prevent warnings/crashes with Luma and some other ReShade mods When using Luma mod and this will be enabled",
    "default": "false",
    "type": "bool"
  },
  {
    "section": "Hotfix",
    "key": "PreferDedicatedGpu",
    "label": "Prefer Dedicated Gpu",
    "description": "OptiScaler will try to force High Performance GPU",
    "default": "false",
    "type": "bool"
  },
  {
    "section": "Hotfix",
    "key": "PreferFirstDedicatedGpu",
    "label": "Prefer First Dedicated Gpu",
    "description": "OptiScaler will report only first High Performance GPU",
    "default": "false",
    "type": "bool"
  },
  {
    "section": "Hotfix",
    "key": "RoundInternalResolution",
    "label": "Round Internal Resolution",
    "description": "Rounds internal resolutions width and height to multiple of this value",
    "default": "disabled",
    "type": "string"
  },
  {
    "section": "Hotfix",
    "key": "SkipFirstFrames",
    "label": "Skip First Frames",
    "description": "Skips upscaling of n frames",
    "default": "disabled",
    "type": "string"
  },
  {
    "section": "Hotfix",
    "key": "RestoreComputeSignature",
    "label": "Restore Compute Signature",
    "description": "Restore last used compute signature after upscaling",
    "default": "false",
    "type": "bool"
  },
  {
    "section": "Hotfix",
    "key": "RestoreGraphicSignature",
    "label": "Restore Graphic Signature",
    "description": "Restore last used graphics signature after upscaling",
    "default": "false",
    "type": "bool"
  },
  {
    "section": "Hotfix",
    "key": "ExtendedStateRestore",
    "label": "Extended State Restore",
    "description": "Tries to track signature changes to fully restore them Useful for games using bindless",
    "default": "false",
    "type": "bool"
  },
  {
    "section": "Hotfix",
    "key": "UsePrecompiledShaders",
    "label": "Use Precompiled Shaders",
    "description": "Use precompiled shaders for RCAS, Output Scaling and Mask Bias",
    "default": "true",
    "type": "bool"
  },
  {
    "section": "Hotfix",
    "key": "ColorResourceBarrier",
    "label": "Color Resource Barrier",
    "description": "Color texture resource state to fix for rainbow colors on AMD cards (for mostly UE games) For UE engine games on AMD, set Color to 4 (D3D12_RESOURCE_STATE_RENDER_TARGET)",
    "default": "auto",
    "type": "string"
  },
  {
    "section": "Hotfix",
    "key": "MotionVectorResourceBarrier",
    "label": "Motion Vector Resource Barrier",
    "description": "For UE engine games on AMD, set MotionVector to 8 (D3D12_RESOURCE_STATE_UNORDERED_ACCESS)",
    "default": "auto",
    "type": "string"
  },
  {
    "section": "Hotfix",
    "key": "DepthResourceBarrier",
    "label": "Depth Resource Barrier",
    "description": "",
    "type": "string",
    "default": "auto",
    "inheritedFrom": "MotionVectorResourceBarrier"
  },
  {
    "section": "Hotfix",
    "key": "ColorMaskResourceBarrier",
    "label": "Color Mask Resource Barrier",
    "description": "",
    "type": "string",
    "default": "auto",
    "inheritedFrom": "DepthResourceBarrier"
  },
  {
    "section": "Hotfix",
    "key": "ExposureResourceBarrier",
    "label": "Exposure Resource Barrier",
    "description": "",
    "type": "string",
    "default": "auto",
    "inheritedFrom": "ColorMaskResourceBarrier"
  },
  {
    "section": "Hotfix",
    "key": "OutputResourceBarrier",
    "label": "Output Resource Barrier",
    "description": "",
    "type": "string",
    "default": "auto",
    "inheritedFrom": "ExposureResourceBarrier"
  }
];
